package com.aerolinea.entidad;
// Generated Mar 4, 2017 11:19:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="aerolinea"
)
public class Usuario  implements java.io.Serializable {

     @NotEmpty(message = "Introduzca nombre de usuario.")
     private String idusuario;
     private Pais pais;
     private Rol rol;
     @NotEmpty(message = "Introduzca nombres.")
     private String nombres;
     private String apellidos;
     @Email(message = "El correo es incorrecto!.")
     private String email;
     @Size(min=8, message="Tamano minimo 8")
     @Digits(integer = 8, fraction = 0, message = "Introduzca solo digitos")
     private String telefono;
     private String clave;
     private Set<Reservacion> reservacions = new HashSet<>(0);

    public Usuario() {
    }

	
    public Usuario(String idusuario, Pais pais, Rol rol, String nombres, String apellidos, String email, String clave) {
        this.idusuario = idusuario;
        this.pais = pais;
        this.rol = rol;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.clave = clave;
    }
    public Usuario(String idusuario, Pais pais, Rol rol, String nombres, String apellidos, String email, String telefono, String clave, Set<Reservacion> reservacions) {
       this.idusuario = idusuario;
       this.pais = pais;
       this.rol = rol;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.telefono = telefono;
       this.clave = clave;
       this.reservacions = reservacions;
    }
   
     @Id 

    
    @Column(name="idusuario", unique=true, nullable=false, length=30)
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpais", nullable=false)
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idrol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="clave", nullable=false, length=100)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }




}


